DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS ApiCall;
DROP TABLE IF EXISTS favoritePlayer;
DROP TABLE IF EXISTS accessLevel;
DROP TABLE IF EXISTS schedule;

CREATE TABLE user(

);